### PR TITLE
Make the route cacheable

### PR DESCRIPTION
**Pull request by jpscharf**
- Use a class function instead of an anonymous function.

### CODE REVIEW

**Comment by mikebronner** [comment]
@jpscharf  Good call! I'll get this merged as soon as possible. :)

**Comment by jpscharf** [comment]
When will this and GeneaLabs/nova-telescope#4 merged?

**Comment by mikebronner** [comment]
@jpscharf I'll try and get to it today. I had a busy weekend migrating servers and websites. :-|

**Comment by mikebronner** [comment]
@jpscharf Thanks again for waiting on this. Try release 0.2.3 and let me know how it works for you. :)

**Pull request closed without merging**
